name: "DuckChat"
version: "${version}-${project.build.number}"
main: "org.cyberiantiger.minecraft.duckchat.Main"
website: "http://dev.bukkit.org/server-mods/duckchat/"
softdepends:
        - Vault
commands:
  duckchat:
    description: The main DuckChat command.
    usage: /<command> channels|channel|chlist|part|join|say|me|msg|reply|reload
    aliases:
            - dc
            - channels
            - channel
            - channellist
            - chlist
            - part
            - join
            - me
            - m
            - msg
            - r
            - reply
            - dcreload
            - t
            - tell
            - whisper
permissions:
        duckchat.channels:
                default: op
                description: Allow usage of the channels command.
        duckchat.channel:
                default: op
                description: Allow usage of the channel command.
        duckchat.join:
                default: op
                description: Allow usage of the join command.
        duckchat.part:
                default: op
                description: Allow usage of the part command.
        duckchat.me:
                default: op
                description: Allow usage of the me command.
        duckchat.message:
                default: op
                description: Allow usage of the message command.
        duckchat.reply:
                default: op
                description: Allow usage of the reply command.
        duckchat.reload:
                default: op
                description: Allow usage of the reload command.
        duckchat.say:
                default: op
                description: Allow usage of the say command.
        duckchat.chat.color:
                default: op
                description: Allow usage of color codes with & in chat.
        duckchat.chat.format:
                default: op
                description: Allow usage of format codes with & in chat.
        duckchat.msg.color:
                default: op
                description: Allow usage of color codes with & in messages.
        duckchat.msg.format:
                default: op
                description: Allow usage of format codes with & in messages.