name: "DuckChat"
version: "${version}-${project.build.number}"
main: "org.cyberiantiger.minecraft.duckchat.bukkit.Main"
website: "http://dev.bukkit.org/server-mods/duckchat/"
softdepend:
        - Vault
commands:
  duckchat:
    description: The main DuckChat command.
    usage: /<command> channels|channel|chlist|part|join|say|me|msg|reply|reload|broadcast|rexec
    aliases:
            - dc
            - channels
            - channel
            - channellist
            - chlist
            - part
            - join
            - me
            - m
            - msg
            - r
            - reply
            - dcreload
            - t
            - tell
            - whisper
            - broadcast
            - bc
            - rexec
permissions:
        duckchat.*:
                default: op
                description: All duckchat permissions.
                children:
                        duckchat.channels: true
                        duckchat.channel: true
                        duckchat.join: true
                        duckchat.part: true
                        duckchat.me: true
                        duckchat.message: true
                        duckchat.reply: true
                        duckchat.reload: true
                        duckchat.say: true
                        duckchat.chat.color: true
                        duckchat.chat.format: true
                        duckchat.msg.color: true
                        duckchat.msg.format: true
                        duckchat.broadcast: true
                        duckchat.broadcast.color: true
                        duckchat.broadcast.format: true
                        duckchat.rexec: true
                        duckchat.spam.bypass: true
        duckchat.channels:
                default: true
                description: Allow usage of the channels command.
        duckchat.channel:
                default: true
                description: Allow usage of the channel command.
        duckchat.join:
                default: true
                description: Allow usage of the join command.
        duckchat.part:
                default: true
                description: Allow usage of the part command.
        duckchat.me:
                default: true
                description: Allow usage of the me command.
        duckchat.message:
                default: true
                description: Allow usage of the message command.
        duckchat.reply:
                default: true
                description: Allow usage of the reply command.
        duckchat.reload:
                default: op
                description: Allow usage of the reload command.
        duckchat.say:
                default: op
                description: Allow usage of the say command.
        duckchat.chat.color:
                default: op
                description: Allow usage of color codes with & in chat.
        duckchat.chat.format:
                default: op
                description: Allow usage of format codes with & in chat.
        duckchat.msg.color:
                default: op
                description: Allow usage of color codes with & in messages.
        duckchat.msg.format:
                default: op
                description: Allow usage of format codes with & in messages.
        duckchat.broadcast:
                default: op
                description: Allow usage of the broadcast command.
        duckchat.broadcast.color:
                default: op
                description: Allow usage of color codes with & in broadcasts.
        duckchat.broadcast.format:
                default: op
                description: Allow usage of format codes with & in broadcasts.
        duckchat.rexec:
                default: op
                description: Allow usage of the rexec command to execute commands on a remote server as console.
        duckchat.spam.bypass:
                default: op
                description: Allows bypassing of spam channel spam protection limits.